receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans


  # Add file exporter for metrics
  file/metrics:
    path: /tmp/metrics.json
    format: json

  # Optional: Add file exporter for traces too
  file/traces:
    path: /tmp/traces.json
    format: json

  debug:
    verbosity: detailed

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, file/traces ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ file/metrics ]

extensions:
  health_check:
