name: Publish Docker image

on:
  push:
    tags:
      - 'v*'  # This will match tags that start with 'v' (like v1.0.0, v2.3.1, etc.)

jobs:
  push_to_registry:
    if: github.repository_owner == 'rustic-ai'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Remove unnecessary directories to free up space # Free up disk space - https://github.com/actions/runner-images/issues/2840
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dragonscaleai/rustic-ai
          tags: type=ref,event=tag

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/dragonscaleai/rustic-ai
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
