name: Publish All Python Packages

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and Publish All Python Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12.10']
    permissions:
      contents: read
      id-token: write  # For PyPI trusted publishing

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          plugins: |
            poetry-plugin-mono-repo-deps@0.3.2

      - name: Build all packages
        run: |
          ./scripts/poetry_install.sh
          ./scripts/poetry_build.sh

      - name: Publish all packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          skip-existing: true
          verbose: true
